"""Parse markdown sources and render per-target subagent files."""

import os
import re
import stat
import tempfile
from copy import deepcopy
from difflib import unified_diff
from io import StringIO
from pathlib import Path

import tomli_w
from pydantic import BaseModel, ConfigDict, Field, InstanceOf
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap
from ruamel.yaml.error import YAMLError

from supagents.config import (
    DEFAULT_TARGETS,
    Config,
    Scope,
    TargetConfig,
    output_dir,
    source_root,
)

SOURCE_FILENAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*\.md$")
MARKER_PREFIX = "# Generated by supagents from "
MARKER_SUFFIX = ". Do not edit; edit the source instead."
DIRECTIVES: tuple[str, ...] = ("OUTPUT", "APPEND_BODY")

_yaml = YAML(typ="rt")
_yaml.indent(mapping=2, sequence=4, offset=2)
_yaml.preserve_quotes = True
_yaml.width = 4096


class ParseError(Exception):
    """Raised when a source file cannot be parsed and must be skipped."""


class DuplicateSourceError(Exception):
    """Two source files would resolve to the same name."""


class TargetBlock(BaseModel):
    """One target's parsed frontmatter and directives."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    frontmatter: InstanceOf[CommentedMap]
    output: str | None = None
    append_body: str | None = None


class Source(BaseModel):
    """A parsed source file ready to be rendered for each target."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    path: Path
    name: str
    rel_path: Path
    shared_frontmatter: InstanceOf[CommentedMap]
    body: str
    targets: dict[str, TargetBlock] = Field(default_factory=dict)
    warnings: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)


class Plan(BaseModel):
    """A single (source x target) emission plan."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    source: Source
    target_name: str
    target: TargetConfig
    output_path: Path
    rendered: str


class BuildSummary(BaseModel):
    """Aggregated results from a build run."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    sources: list[Source] = Field(default_factory=list)
    plans: list[Plan] = Field(default_factory=list)
    written: list[Path] = Field(default_factory=list)
    skipped_unchanged: list[Path] = Field(default_factory=list)
    orphans: list[Path] = Field(default_factory=list)
    fatal_errors: list[tuple[Path, str]] = Field(default_factory=list)

    @property
    def error_count(self) -> int:
        return sum(1 for s in self.sources if s.errors)

    @property
    def warning_count(self) -> int:
        return sum(len(s.warnings) for s in self.sources)


def dump_yaml(data: CommentedMap) -> str:
    """Dump a frontmatter mapping using project conventions."""
    sio = StringIO()
    _yaml.dump(data, sio)
    return sio.getvalue()


def split_frontmatter(text: str) -> tuple[str, str]:
    """Split source text into ``(frontmatter, body)``.

    Raises ``ParseError`` if the delimiters are missing or malformed.
    """
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = text.split("\n")
    if not lines or lines[0].rstrip() != "---":
        raise ParseError("source must begin with '---' frontmatter delimiter")
    for i in range(1, len(lines)):
        if lines[i].rstrip() == "---":
            return "\n".join(lines[1:i]), "\n".join(lines[i + 1 :]).strip("\n")
    raise ParseError("missing closing '---' frontmatter delimiter")


def _parse_frontmatter(text: str) -> CommentedMap:
    """Load YAML frontmatter as a ``CommentedMap`` (empty if blank)."""
    if not text.strip():
        return CommentedMap()
    try:
        result = _yaml.load(text)
    except YAMLError as e:
        raise ParseError(f"invalid YAML frontmatter: {e}") from e
    if result is None:
        return CommentedMap()
    if not isinstance(result, CommentedMap):
        raise ParseError("frontmatter must be a YAML mapping at the top level")
    return result


def _parse_target_block(name: str, value: object, src: Source) -> TargetBlock | None:
    """Parse one target block, appending warnings/errors to ``src``.

    Returns ``None`` if the target should be skipped entirely.
    """
    if value is None:
        return TargetBlock(frontmatter=CommentedMap())
    if not isinstance(value, CommentedMap):
        src.warnings.append(
            f"target {name!r} must be a YAML mapping (got {type(value).__name__}); skipping"
        )
        return None

    fm = CommentedMap()
    output: str | None = None
    append_body: str | None = None
    for k, v in value.items():
        if not isinstance(k, str):
            src.warnings.append(f"non-string key {k!r} in target {name!r} ignored")
            continue
        if not k.isupper():
            fm[k] = v
            continue
        match k:
            case "OUTPUT":
                if not isinstance(v, str):
                    src.errors.append(
                        f"directive 'OUTPUT' in target {name!r} must be a string; "
                        f"skipping this target's emit"
                    )
                    return None
                output = v
            case "APPEND_BODY":
                if v is None:
                    append_body = ""
                elif isinstance(v, str):
                    append_body = v
                else:
                    src.warnings.append(
                        f"directive 'APPEND_BODY' in target {name!r} must be a string; ignored"
                    )
            case _:
                src.warnings.append(
                    f"unknown directive {k!r} in target {name!r} (known: {', '.join(DIRECTIVES)})"
                )
    return TargetBlock(frontmatter=fm, output=output, append_body=append_body)


def parse_source(path: Path, root: Path, known_targets: set[str] | None = None) -> Source:
    """Read and parse a source file into a ``Source`` value.

    Raises ``ParseError`` for failures that prevent any output (bad YAML,
    empty body, bad filename). Per-target warnings and errors are collected
    on the returned ``Source``.
    """
    if known_targets is None:
        known_targets = set(DEFAULT_TARGETS)
    if not SOURCE_FILENAME_RE.match(path.name):
        raise ParseError(
            f"source filename must match ^[a-z0-9][a-z0-9_-]*\\.md$ (got {path.name!r})"
        )

    text = path.read_text(encoding="utf-8").removeprefix("\ufeff")
    fm_text, body = split_frontmatter(text)
    if not body.strip():
        raise ParseError("body must contain non-whitespace content")
    fm = _parse_frontmatter(fm_text)

    try:
        rel_path = path.resolve().relative_to(root.resolve())
    except ValueError:
        rel_path = Path(path.name)

    src = Source(
        path=path,
        name=path.stem,
        rel_path=rel_path,
        shared_frontmatter=CommentedMap(),
        body=body,
    )

    for key, value in fm.items():
        if not isinstance(key, str):
            src.warnings.append(f"non-string top-level key {key!r} ignored")
            continue
        if not key.isupper():
            src.shared_frontmatter[key] = value
            continue
        if key not in known_targets:
            src.warnings.append(
                f"unknown top-level key {key!r} (known targets: {', '.join(sorted(known_targets))})"
            )
            continue
        block = _parse_target_block(key, value, src)
        if block is not None:
            src.targets[key] = block
    return src


def marker_line(rel_path: Path) -> str:
    """The marker comment placed on the first line inside the frontmatter."""
    return f"{MARKER_PREFIX}{rel_path.as_posix()}{MARKER_SUFFIX}"


def has_marker(text: str) -> bool:
    """True if ``text``'s frontmatter contains the supagents marker comment.

    Tolerates reformatting that moves the marker elsewhere within the
    frontmatter block (e.g. another tool sorting YAML keys).
    """
    first = text.split("\n", 1)[0]
    if first.startswith(MARKER_PREFIX) and first.endswith(MARKER_SUFFIX):
        return True
    if not text.startswith("---\n"):
        return False
    for line in text.split("\n", 1)[1].split("\n"):
        if line.rstrip() == "---":
            return False
        if line.startswith(MARKER_PREFIX) and line.endswith(MARKER_SUFFIX):
            return True
    return False


def compute_frontmatter(shared: CommentedMap, target_fm: CommentedMap) -> CommentedMap:
    """Merge shared + target frontmatter; target overrides; shared keys keep their position."""
    out = CommentedMap()
    for k, v in shared.items():
        out[k] = deepcopy(v)
    for k, v in target_fm.items():
        out[k] = deepcopy(v)
    return out


def compute_body(shared_body: str, append_body: str | None) -> str:
    """Concatenate shared body + optional ``APPEND_BODY``, separated by one blank line."""
    if not append_body:
        return shared_body
    tail = append_body.strip("\n")
    if not tail:
        return shared_body
    return f"{shared_body.rstrip('\n')}\n\n{tail}"


def render(
    rel_path: Path, frontmatter: CommentedMap, body: str, target: TargetConfig | None = None
) -> str:
    """Produce the full file contents for one output."""
    if target is not None and target.format == "toml":
        if target.body_key in frontmatter:
            raise ParseError(f"{target.body_key!r} is reserved for the source body")
        try:
            data = dict(frontmatter)
            data[target.body_key] = body.rstrip("\n") + "\n"
            return marker_line(rel_path) + "\n" + tomli_w.dumps(data, multiline_strings=True)
        except (TypeError, ValueError) as e:
            raise ParseError(f"frontmatter cannot be represented as TOML: {e}") from e
    fm_text = dump_yaml(frontmatter) if frontmatter else ""
    return f"---\n{marker_line(rel_path)}\n{fm_text}---\n\n{body.rstrip('\n')}\n"


def resolve_output_path(
    source: Source,
    target: TargetConfig,
    scope: Scope,
    cwd: Path,
    output_directive: str | None,
) -> Path:
    """Where the rendered file for ``target`` should land."""
    if output_directive is not None:
        p = Path(output_directive).expanduser()
        if not p.is_absolute():
            p = source.path.parent / p
        return p
    return output_dir(target, scope, cwd) / f"{source.name}{target.filename_suffix}"


def _scope_root(scope: Scope, cwd: Path) -> Path:
    """The directory an OUTPUT directive should not escape, by scope."""
    return cwd if scope == "project" else Path.home()


def would_change(path: Path, content: str) -> bool:
    """True if writing ``content`` to ``path`` would alter the on-disk file."""
    if not path.exists():
        return True
    try:
        return path.read_text(encoding="utf-8") != content
    except (OSError, UnicodeError):
        return True


def output_diff(path: Path, content: str) -> str:
    """Preview an addition, edit, or removal without changing the filesystem."""
    exists = path.exists()
    previous = path.read_text(encoding="utf-8") if exists else ""
    lines = unified_diff(
        previous.splitlines(keepends=True),
        content.splitlines(keepends=True),
        fromfile=str(path) if exists else "/dev/null",
        tofile=str(path) if content else "/dev/null",
    )
    return "".join(
        line if line.endswith("\n") else line + "\n\\ No newline at end of file\n" for line in lines
    )


def atomic_write(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` atomically. Return True if the file changed."""
    if not would_change(path, content):
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, delete=False
    ) as tf:
        tmp = Path(tf.name)
        try:
            tf.write(content)
        except OSError:
            tmp.unlink(missing_ok=True)
            raise
    # NamedTemporaryFile creates files at 0600; honor the user's umask instead
    # so generated dotfiles get the conventional 0644 (or whatever umask yields).
    umask = os.umask(0)
    os.umask(umask)
    try:
        tmp.chmod(0o666 & ~umask)
    except OSError:
        tmp.unlink(missing_ok=True)
        raise
    try:
        tmp.replace(path)
    except OSError:
        tmp.unlink(missing_ok=True)
        raise
    return True


def list_sources(root: Path) -> list[Path]:
    """Enumerate sources without hiding filesystem failures or dangling links."""
    return sorted(
        path
        for path in root.iterdir()
        if path.suffix == ".md" and (path.is_symlink() or stat.S_ISREG(path.stat().st_mode))
    )


def plan_source(
    source: Source,
    config: Config,
    scope: Scope,
    cwd: Path,
    targets: set[str] | None = None,
) -> list[Plan]:
    """Compute every ``Plan`` (source x target) that would be emitted."""
    plans: list[Plan] = []
    for tname, block in source.targets.items():
        if targets is not None and tname not in targets:
            continue
        target = config.targets[tname]
        try:
            out_path = resolve_output_path(source, target, scope, cwd, block.output)
            resolved = out_path.resolve()
        except (OSError, ValueError, RuntimeError) as e:
            source.errors.append(f"{tname}: invalid output path: {e}")
            continue
        if block.output is not None:
            root = _scope_root(scope, cwd)
            try:
                resolved.relative_to(root.expanduser().resolve())
            except ValueError:
                source.warnings.append(
                    f"target {tname!r} OUTPUT {block.output!r} resolves outside "
                    f"{root} ({out_path}); verify this is intentional"
                )
        fm = compute_frontmatter(source.shared_frontmatter, block.frontmatter)
        body = compute_body(source.body, block.append_body)
        if tname == "CODEX" and any(
            not isinstance(fm.get(key), str) or not fm[key].strip()
            for key in ("name", "description")
        ):
            source.errors.append("CODEX requires non-empty name and description strings")
            continue
        try:
            rendered = render(source.rel_path, fm, body, target)
        except ParseError as e:
            source.errors.append(f"{tname}: {e}")
            continue
        plans.append(
            Plan(
                source=source,
                target_name=tname,
                target=target,
                output_path=out_path,
                rendered=rendered,
            )
        )
    return plans


def collect_sources(
    scope: Scope, config: Config, cwd: Path, source_dir: Path | None = None
) -> tuple[list[Source], list[tuple[Path, str]]]:
    """Parse every source in ``scope``. Returns ``(sources, fatal_errors)``."""
    root = source_dir or source_root(scope, cwd)
    if source_dir is not None and not root.is_dir():
        return [], [(root, "source directory does not exist")]
    sources: list[Source] = []
    fatal_errors: list[tuple[Path, str]] = []
    seen: dict[str, Path] = {}
    known_targets = set(config.targets)
    try:
        paths = list_sources(root)
    except FileNotFoundError as e:
        if source_dir is None and not root.exists() and not root.is_symlink():
            return [], []
        return [], [(root, str(e))]
    except OSError as e:
        return [], [(root, str(e))]
    for path in paths:
        try:
            src = parse_source(path, root, known_targets)
        except (ParseError, OSError, UnicodeError) as e:
            fatal_errors.append((path, str(e)))
            continue
        if src.name in seen:
            raise DuplicateSourceError(
                f"duplicate source name {src.name!r}: {seen[src.name]} and {src.path}"
            )
        seen[src.name] = src.path
        sources.append(src)
    return sources, fatal_errors


def build(
    scope: Scope,
    config: Config | None = None,
    cwd: Path | None = None,
    dry_run: bool = False,
    targets: set[str] | None = None,
    source_dir: Path | None = None,
    strict: bool = False,
) -> BuildSummary:
    """Run the build for all sources in ``scope``.

    In dry-run mode, ``written`` and ``skipped_unchanged`` still reflect what
    *would* change so callers can detect drift without touching the filesystem.
    """
    config = config or Config.load()
    cwd = cwd or Path.cwd()
    summary = BuildSummary()
    summary.sources, summary.fatal_errors = collect_sources(scope, config, cwd, source_dir)

    for src in summary.sources:
        summary.plans.extend(plan_source(src, config, scope, cwd, targets))
    # Validate the complete plan before changing anything. A marker establishes
    # generator ownership, not a security boundary against a concurrent writer.
    outputs: set[Path] = set()
    inputs = {src.path.resolve() for src in summary.sources}
    for plan in summary.plans:
        path = plan.output_path
        resolved = path.resolve()
        problem = None
        if resolved in inputs:
            problem = "output would overwrite a source"
        elif resolved in outputs:
            problem = "multiple outputs resolve to the same path"
        elif path.is_symlink():
            problem = "refusing to replace a symlink"
        elif path.exists():
            try:
                if not has_marker(path.read_text(encoding="utf-8")):
                    problem = "refusing to overwrite a file not generated by supagents"
            except (OSError, UnicodeError):
                problem = "existing output is not a readable UTF-8 file"
        outputs.add(resolved)
        if problem:
            summary.fatal_errors.append((path, problem))
    if summary.fatal_errors or summary.error_count or (strict and summary.warning_count):
        return summary
    for plan in summary.plans:
        try:
            changed = (
                would_change(plan.output_path, plan.rendered)
                if dry_run
                else atomic_write(plan.output_path, plan.rendered)
            )
        except OSError as e:
            summary.fatal_errors.append((plan.output_path, f"write failed: {e}"))
            break
        (summary.written if changed else summary.skipped_unchanged).append(plan.output_path)
    return summary


def check(
    scope: Scope,
    config: Config | None = None,
    cwd: Path | None = None,
    targets: set[str] | None = None,
    source_dir: Path | None = None,
) -> BuildSummary:
    """Check expected outputs and configured directories for drift without writes.

    Require existing sources so a missing checkout never passes a CI gate.
    Orphan discovery is limited to the current configured output directories.
    """
    config = config or Config.load()
    cwd = cwd or Path.cwd()
    summary = build(
        scope,
        config,
        cwd,
        dry_run=True,
        targets=targets,
        source_dir=source_dir or source_root(scope, cwd),
    )
    if summary.fatal_errors or summary.error_count:
        return summary
    # Ambiguous sources cannot establish which outputs are obsolete. Ordinary
    # checks report warnings; strict checks reject them at the CLI boundary.
    if not summary.warning_count:
        try:
            summary.orphans = _scan_orphans(summary.sources, scope, config, cwd, targets)
        except (OSError, ValueError, RuntimeError) as e:
            summary.fatal_errors.append((source_dir or source_root(scope, cwd), str(e)))
    return summary


def _scan_orphans(
    sources: list[Source], scope: Scope, config: Config, cwd: Path, targets: set[str] | None
) -> list[Path]:
    # Different targets may share a directory. A target filter narrows scanning,
    # but must never classify another target's current output as obsolete.
    expected = {
        resolve_output_path(src, config.targets[name], scope, cwd, block.output).resolve()
        for src in sources
        for name, block in src.targets.items()
    }
    orphans: set[Path] = set()
    for tname, target in config.targets.items():
        if targets is not None and tname not in targets:
            continue
        out_dir = output_dir(target, scope, cwd)
        try:
            candidates = sorted(out_dir.iterdir())
        except FileNotFoundError:
            if out_dir.is_symlink():
                raise
            continue
        for candidate in candidates:
            if not candidate.name.endswith(target.filename_suffix) or candidate.is_symlink():
                continue
            if not stat.S_ISREG(candidate.stat().st_mode):
                continue
            try:
                content = candidate.read_text(encoding="utf-8")
            except UnicodeError:
                # Binary files cannot contain a valid generated text header.
                continue
            if has_marker(content) and candidate.resolve() not in expected:
                orphans.add(candidate)
    return sorted(orphans)


def find_orphans(
    scope: Scope,
    config: Config | None = None,
    cwd: Path | None = None,
    targets: set[str] | None = None,
    source_dir: Path | None = None,
) -> list[Path]:
    """Marker-bearing output files for which no source still produces an output."""
    config = config or Config.load()
    cwd = cwd or Path.cwd()
    # Cleanup requires an existing, readable source directory. Missing inputs
    # cannot establish that the user deliberately removed every source.
    sources, errors = collect_sources(scope, config, cwd, source_dir or source_root(scope, cwd))
    if errors:
        raise ParseError("cannot clean while sources are unreadable or invalid")
    for src in sources:
        plan_source(src, config, scope, cwd, targets)

    if any(src.errors or src.warnings for src in sources):
        raise ParseError("cannot clean while sources have errors or warnings")
    try:
        return _scan_orphans(sources, scope, config, cwd, targets)
    except (OSError, ValueError, RuntimeError) as e:
        raise ParseError(f"cannot inspect output directories: {e}") from e
